spring:
  application:
    name: MeMiLog

  cloud:
    gcp:
      project-id: memilog
      storage:
        credentials:
          location: classpath:memilog-292b5416c430.json
        bucket: memilog

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: mapper/**/*.xml

server:
  max-http-request-header-size: 40KB