spring:
  application:
    name: MeMiLog

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: mapper/**/*.xml

server:
  max-http-request-header-size: 40KB

logging:
  level:
    root: debug